### ISSUE TITLE
Failing to build with org.freedesktop.Sdk 25.08 and Sep. 4 shared-modules

### ISSUE THREAD

**Issue by riomccloud** [flathub/org.srb2.SRB2Persona#25]
After updating dependencies, the game fails to build. It works fine with SDK v23.08 and older shared-modules.
Related PR: https://github.com/flathub/org.srb2.SRB2Persona/pull/24
Action URL: https://github.com/flathub-infra/vorarbeiter/actions/runs/17871504747

```
s_sound.c: In function ‘S_GetMusicLumpNum’:
s_sound.c:2124:24: error: implicit declaration of function ‘W_GetNumForNameMusic’; did you mean ‘W_CheckNumForNameMusic’? [-Wimplicit-function-declaration]
 2124 |                 return W_GetNumForNameMusic(va(midipref ? "d_%s":"o_%s", mname));
      |                        ^~~~~~~~~~~~~~~~~~~~
      |                        W_CheckNumForNameMusic
s_sound.c:2124:24: warning: nested extern declaration of ‘W_GetNumForNameMusic’ [-Wnested-externs]
make: *** [Makefile:396: ../make/linux/64/SDL/objs/./s_sound.o] Error 1
make: *** Waiting for unfinished jobs....
w_wad.c:1503:11: warning: no previous prototype for ‘W_GetNumForNameMusic’ [-Wmissing-prototypes]
 1503 | lumpnum_t W_GetNumForNameMusic(const char *name)
      |           ^~~~~~~~~~~~~~~~~~~~
w_wad.c: In function ‘ResGetLumpsZip’:
w_wad.c:660:25: warning: pointer ‘fullname’ may be used after ‘free’ [-Wuse-after-free]
  660 |                         CONS_Alert(CONS_WARNING, "%s: Unsupported compression method\n", fullname);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
w_wad.c:644:17: note: call to ‘free’ here
  644 |                 free(fullname);
      |                 ^~~~~~~~~~~~~~
v_video.c: In function ‘V_SRB2PgenericStringWidth’:
v_video.c:2461:19: warning: unused variable ‘lumpnum’ [-Wunused-variable]
 2461 |         lumpnum_t lumpnum;
      |                   ^~~~~~~
make: Leaving directory '/run/build/srb2persona/src'
Error: module srb2persona: Child process exited with code 2
error: Recipe `build` failed with exit code 1
Error: Process completed with exit code 1.
```

**Comment by riomccloud** [comment]
Fixed by #27
